/**
 * Spanish umbrella lexicon for the closeness recap (see lexicon.ts): when a player guesses a broad
 * class ("animales", "comida", "instrumentos"), we check how many of the category's clue words belong
 * to it. Each line: guess aliases | member vocabulary. Words are stemmed at load (Spanish stemmer), so
 * plural and gender forms don't matter. Original content for this project.
 */
import { makeLexicon, parseUmbrellas, type Lexicon } from './lexicon';
import { spanishMatcher } from './match.es';

const SRC = `
animal,animales,bicho,fauna,criatura,bestia,mamifero,mascota,zoologico,especie|perro,gato,tigre,cebra,león,oso,lobo,zorro,caballo,vaca,cerdo,oveja,cabra,toro,rinoceronte,elefante,jirafa,mono,gorila,chimpancé,orangután,canguro,koala,panda,ardilla,conejo,liebre,ratón,rata,hámster,erizo,puercoespín,murciélago,venado,alce,camello,llama,alpaca,vicuña,guanaco,burro,mula,leopardo,guepardo,jaguar,puma,lince,ocelote,hiena,nutria,castor,mapache,zarigüeya,tlacuache,foca,morsa,ballena,delfín,orca,tiburón,pez,salmón,atún,pulpo,calamar,cangrejo,langosta,camarón,caracol,estrella de mar,medusa,tortuga,lagartija,iguana,serpiente,cobra,boa,anaconda,cocodrilo,caimán,rana,sapo,camaleón,dragón,unicornio,pájaro,búho,lechuza,águila,halcón,cóndor,loro,guacamaya,tucán,pingüino,avestruz,ñandú,cisne,pato,ganso,gallina,gallo,pollito,pavo,guajolote,pavo real,paloma,flamenco,colibrí,abeja,avispa,hormiga,mariposa,polilla,catarina,escarabajo,mosca,mosquito,grillo,araña,alacrán,capibara,tapir,perezoso,armadillo,oso hormiguero,chinchilla,cuyo,piraña,manatí,vizcacha,dálmata,chihuahua,labrador,poodle,cachorro,gatito,potro,cordero,ternero,lechón
ave,aves,pajaro,volatil,plumifero|búho,lechuza,águila,halcón,gavilán,cóndor,loro,guacamaya,tucán,quetzal,pingüino,avestruz,ñandú,emú,kiwi,cisne,pato,ganso,gallina,gallo,pavo,guajolote,pavo real,paloma,flamenco,colibrí,pelícano,canario,gorrión,cuervo,gaviota,cigüeña,garza,dodo,casuario,cernícalo,milano,pájaro carpintero,pollito
insecto,bicho,plaga|abeja,avispa,hormiga,mariposa,polilla,catarina,escarabajo,mosca,mosquito,grillo,chapulín,cigarra,libélula,luciérnaga,cucaracha,pulga,piojo,termita,oruga,araña,alacrán,garrapata,langosta,mantis
mar,oceano,marino,acuatico,agua,playa,submarino|pez,tiburón,ballena,delfín,orca,foca,morsa,pulpo,calamar,cangrejo,langosta,camarón,ostra,almeja,mejillón,estrella de mar,medusa,coral,caballito de mar,erizo,tortuga,salmón,atún,sardina,manatí,barco,submarino,ola,marea,arrecife,concha,perla,ancla,vela,isla,playa,arena
comida,alimento,platillo,plato,cocina,comer,comestible,ingrediente,receta,gastronomia,snack,botana,antojito|pan,queso,pizza,pasta,arroz,frijol,huevo,tocino,jamón,salchicha,chorizo,hamburguesa,sándwich,taco,burrito,tamal,enchilada,quesadilla,torta,sopa,caldo,ensalada,carne,pollo,pescado,camarón,mariscos,fideo,espagueti,lasaña,ravioles,pastel,galleta,dona,panqué,hot cake,waffle,cereal,avena,yogur,mantequilla,crema,leche,chocolate,dulce,caramelo,cajeta,miel,mermelada,azúcar,sal,pimienta,mostaza,cátsup,mayonesa,salsa,chile,guacamole,palomitas,papas,cacahuate,almendra,nuez,aceituna,cebolla,ajo,papa,tomate,zanahoria,elote,maíz,manzana,plátano,naranja,limón,uva,fresa,mango,piña,coco,aguacate,empanada,arepa,ceviche,asado,milanesa,alfajor,churro,flan,pozole,mole,chilaquiles,tortilla,totopo,nacho,helado,paleta,gelatina,arroz con leche,tres leches,choripán,locro,ajiaco,sancocho,hallaca,cachapa,tequeños,completo,pastel de choclo,mofongo,tostones,lechón,chicharrón,croquetas,puré,ñoquis,cotija,panela,oaxaca,manchego,parmesano,gouda,cheddar,mozzarella,roquefort,requesón,cemita,bolillo,concha,telera,marraqueta,medialuna
fruta,frutas,frutal|manzana,plátano,banana,naranja,limón,lima,toronja,mandarina,uva,cereza,fresa,frambuesa,zarzamora,arándano,mora,melón,sandía,durazno,pera,ciruela,chabacano,mango,piña,coco,kiwi,higo,dátil,aguacate,granada,papaya,guayaba,maracuyá,guanábana,pitahaya,mamey,lulo,chirimoya,tuna,membrillo,pasas,tamarindo,grosella,kumquat,bergamota
verdura,verduras,vegetal,vegetales,hortaliza,legumbre|papa,tomate,zanahoria,chícharo,elote,maíz,cebolla,ajo,lechuga,col,espinaca,brócoli,coliflor,pepino,calabaza,calabacita,chile,pimiento,kale,acelga,arúgula,berro,betabel,rábano,apio,poro,camote,yuca,jengibre,alcachofa,espárrago,berenjena,nopal,champiñón,frijol,lenteja,garbanzo,haba,ejote
bebida,bebidas,trago,tomar,refresco,alcohol,coctel,licor,jugo|agua,leche,té,café,expreso,capuchino,latte,americano,cortado,refresco,limonada,jugo,vino,cerveza,sidra,whisky,vodka,ginebra,ron,tequila,mezcal,pisco,pulque,champaña,sangría,mojito,margarita,piña colada,horchata,atole,champurrado,chocolate,mate,tereré,chicha,agua de jamaica,licuado,malteada,carajillo
cuerpo,anatomia,organo,organos,extremidad,humano|cabeza,cara,ojo,oreja,nariz,boca,labio,lengua,diente,muela,colmillo,barbilla,mejilla,frente,ceja,pestaña,párpado,sien,cuello,garganta,hombro,brazo,codo,muñeca,mano,dedo,pulgar,uña,pecho,espalda,columna,estómago,panza,cadera,pierna,rodilla,tobillo,pie,talón,piel,pelo,cerebro,corazón,pulmón,hígado,riñón,hueso,costilla,cráneo,músculo,sangre,vena,fémur,tibia,peroné,húmero,cúbito,clavícula,bíceps,tríceps,glúteo,pupila,iris,retina,córnea
ropa,prenda,prendas,vestimenta,vestir,moda,atuendo,accesorio|camisa,playera,camiseta,blusa,suéter,sudadera,chamarra,chaqueta,abrigo,saco,traje,chaleco,vestido,falda,pantalón,jeans,short,calcetín,zapato,bota,tenis,sandalia,chancla,pantufla,huarache,sombrero,gorra,gorro,boina,casco,bufanda,guante,corbata,cinturón,pijama,delantal,uniforme,poncho,rebozo,sarape,huipil,guayabera,pollera,chullo,capa,cuello,manga,botón,cierre,bolsillo,velo,bata,chal,media,liga,remera,polera,franela,playera
vehiculo,transporte,vehiculos,medio transporte,viaje|carro,auto,coche,camión,autobús,camioneta,taxi,tren,tranvía,metro,bicicleta,moto,motocicleta,patineta,scooter,avión,avioneta,helicóptero,barco,lancha,velero,canoa,kayak,balsa,submarino,cohete,tractor,tanque,ambulancia,patrulla,trineo,carreta,carruaje,globo,teleférico,guagua,colectivo,micro,combi
herramienta,herramientas,utensilio,instrumento,aparato,ferreteria|martillo,serrucho,sierra,taladro,desarmador,llave inglesa,pinzas,cincel,hacha,pala,rastrillo,azadón,nivel,cinta métrica,regla,lija,tornillo,clavo,tuerca,escalera,brocha,escoba,trapeador,cubeta,peine,navaja,tijeras,aguja,espátula,batidor,cucharón,tenedor,cuchara,cuchillo,rallador,colador,sacacorchos,destapador,compás,transportador
instrumento,instrumentos,musica,musical,banda,orquesta,cancion,ritmo|piano,guitarra,violín,viola,chelo,contrabajo,arpa,tambor,batería,flauta,clarinete,oboe,fagot,saxofón,trompeta,trombón,tuba,corno,armónica,acordeón,bandoneón,banjo,ukulele,mandolina,órgano,teclado,xilófono,marimba,triángulo,pandero,platillos,maracas,güiro,cajón,bongó,congas,timbales,charango,quena,zampoña,cuatro,vihuela,guitarrón,laúd,campana,gong,nota,escala,acorde,melodía,salsa,cumbia,tango,merengue,bachata,bolero,reguetón,rock,jazz,pop,rap,ópera,mariachi,son
deporte,deportes,juego,atletismo,atleta,equipo,olimpiada,olimpico|fútbol,béisbol,básquetbol,tenis,golf,hockey,rugby,voleibol,bádminton,boxeo,lucha,judo,karate,taekwondo,esgrima,tiro con arco,ciclismo,remo,vela,surf,esquí,snowboard,patinaje,natación,clavados,buceo,maratón,relevos,vallas,jabalina,disco,bala,polo,squash,pádel,frontón,raquetbol,boliche,dardos,billar,gimnasia,triatlón,ajedrez,pelota,bate,raqueta,portería,gol,red,canasta
color,colores,tono,tonos,tonalidad,pintura,matiz|rojo,naranja,amarillo,verde,azul,morado,violeta,añil,rosa,café,marrón,negro,blanco,gris,plata,dorado,oro,beige,crema,marfil,marino,turquesa,celeste,magenta,granate,carmesí,escarlata,lavanda,lila,malva,coral,durazno,salmón,oliva,lima,menta,ámbar,rubí,esmeralda,zafiro,jade,ocre,vino,cereza,uva,cielo,rey,petróleo,cobalto,bermellón,carmín,musgo,pistache,chocolate,caramelo,canela,avellana
pais,paises,nacion,lugar,geografia,capital,ciudad,continente,territorio,mundo,region|méxico,guatemala,honduras,el salvador,nicaragua,costa rica,panamá,cuba,puerto rico,república dominicana,colombia,venezuela,ecuador,perú,bolivia,chile,argentina,uruguay,paraguay,brasil,españa,francia,italia,alemania,portugal,grecia,suiza,hungría,austria,inglaterra,rusia,china,japón,corea,india,vietnam,tailandia,nepal,mongolia,egipto,marruecos,kenia,nigeria,ghana,etiopía,senegal,sudáfrica,chad,madagascar,islandia,jamaica,filipinas,canadá,estados unidos,bogotá,lima,quito,caracas,santiago,montevideo,asunción,la paz,brasilia,parís,roma,madrid,berlín,lisboa,londres,atenas,viena,varsovia,tokio,pekín,seúl,europa,asia,áfrica,américa,oceanía,antártida,jalisco,oaxaca,yucatán,mendoza,córdoba,medellín,cali,cartagena,monterrey,guadalajara
trabajo,profesion,oficio,ocupacion,empleo,carrera,trabajador|doctor,médico,enfermera,maestro,maestra,abogado,juez,chef,cocinero,panadero,carnicero,campesino,granjero,piloto,chofer,capitán,marinero,soldado,policía,detective,bombero,plomero,carpintero,electricista,mecánico,ingeniero,arquitecto,artista,pintor,escritor,poeta,actor,cantante,bailarín,músico,dentista,veterinario,cirujano,científico,cajero,mesero,sastre,zapatero,herrero,albañil,barbero,cartero,árbitro,entrenador,rey,reina,príncipe,princesa,presidente,alcalde,pediatra,radiólogo,camillero,sommelier
planta,plantas,flor,flores,arbol,arboles,botanica,jardin,naturaleza,vegetacion,flora|rosa,tulipán,margarita,lirio,orquídea,girasol,dalia,cempasúchil,nochebuena,bugambilia,jazmín,lavanda,diente de león,trébol,hiedra,helecho,musgo,cactus,nopal,bambú,pasto,roble,pino,abeto,sauce,palmera,ceiba,jacaranda,ahuehuete,ombú,araucaria,olivo,eucalipto,caoba,cedro,semilla,raíz,tallo,hoja,rama,tronco,corteza,espina,pétalo,polen,estambre,pistilo,sépalo,hierba,albahaca,menta,romero,tomillo,orégano,cilantro,perejil,epazote,laurel
casa,hogar,mueble,muebles,vivienda,cuarto,habitacion|mesa,silla,sofá,sillón,cama,escritorio,banco,repisa,librero,ropero,clóset,cómoda,cajón,espejo,lámpara,tapete,alfombra,cortina,almohada,cojín,cobija,sábana,colchón,cuna,lavabo,tina,regadera,inodoro,estufa,horno,refrigerador,microondas,licuadora,tostadora,puerta,ventana,techo,pared,piso,escalera,ático,sótano,cochera,cocina,recámara,baño,sala,comedor,chimenea,balcón,patio,fachada,cimientos
clima,tiempo,meteorologia,pronostico,cielo|lluvia,nieve,granizo,niebla,neblina,nube,tormenta,trueno,relámpago,rayo,viento,brisa,huracán,tornado,ciclón,ventisca,llovizna,sol,helada,hielo,calor,humedad,arcoíris,sequía,inundación,rocío,cúmulo,cirro,estrato,nimbo
espacio,astronomia,universo,cosmos,galaxia,cielo,estrellas|sol,luna,estrella,planeta,cometa,asteroide,meteorito,galaxia,nebulosa,agujero negro,mercurio,venus,tierra,marte,júpiter,saturno,urano,neptuno,plutón,órbita,cohete,astronauta,satélite,telescopio,eclipse,constelación,orión,osa mayor,casiopea,cruz del sur
figura,forma,formas,geometria,poligono|círculo,cuadrado,triángulo,rectángulo,óvalo,rombo,trapecio,estrella,corazón,cruz,hexágono,pentágono,octágono,cubo,esfera,cono,cilindro,pirámide,prisma,espiral,flecha,anillo,línea,curva,arco
numero,numeros,matematicas,cifra,digito,contar,cantidad|uno,dos,tres,cuatro,cinco,seis,siete,ocho,nueve,diez,once,doce,docena,cien,mil,millón,cero,mitad,cuarto,par,impar,primo,suma,resta,división,multiplicación,potencia,raíz
metal,material,elemento,mineral,piedra,roca,joya,gema,sustancia,quimica|oro,plata,cobre,hierro,acero,estaño,plomo,zinc,níquel,aluminio,platino,titanio,bronce,latón,mercurio,oxígeno,hidrógeno,carbono,nitrógeno,helio,neón,argón,sodio,calcio,potasio,madera,vidrio,plástico,papel,algodón,lana,seda,cuero,hule,piedra,mármol,granito,barro,diamante,rubí,esmeralda,zafiro,perla,ópalo,jade,ámbar,cristal,cuarzo,amatista,topacio,carbón,sal,arena
arma,armas,guerra,ejercito,militar,batalla,pelea,combate|espada,cuchillo,daga,lanza,hacha,arco,flecha,pistola,rifle,cañón,bomba,granada,misil,tanque,escudo,armadura,casco,mazo,látigo,bala,torpedo,honda,catapulta,ballesta
juguete,juguetes,infancia,niño,niños,jugar,juego,juegos|muñeca,pelota,papalote,yoyo,rompecabezas,bloques,oso de peluche,trompo,canicas,balero,matatena,perinola,sonaja,columpio,resbaladilla,sube y baja,trampolín,robot,tren,títere,marioneta,muñeca de trapo,lotería,dominó,ajedrez,damas,naipes,dados
personaje,personajes,caricatura,caricaturas,dibujos animados,animacion,pelicula,serie,television,programa,ficcion|homero,bart,lisa,marge,chavo,quico,chilindrina,mafalda,condorito,mickey,woody,buzz,shrek,simba,elsa,olaf,goku,vegeta,pikachu,mario,luigi,batman,superman,guasón,harry potter,hermione,yoda,frodo,gandalf,piolín,bugs bunny,pato lucas,elmo,pinocho,cenicienta,caperucita roja,blancanieves
dios,dioses,mitologia,mito,mitos,leyenda,deidad|zeus,hera,atenea,apolo,poseidón,hades,afrodita,ares,hermes,júpiter,juno,minerva,marte,venus,neptuno,mercurio,plutón,baco,odín,thor,loki,freya,quetzalcóatl,tláloc,huitzilopochtli,tezcatlipoca,inti,viracocha,pachamama,dragón,unicornio,sirena,fénix,centauro,minotauro,pegaso,grifo,hidra,llorona,chupacabras
`;

export const UMBRELLAS_ES = parseUmbrellas(SRC, spanishMatcher.tokenize);

export const spanishLexicon: Lexicon = makeLexicon(UMBRELLAS_ES);
